# LLM settings
gemini:
  use_gemini: false
  gemini_api_key_env: "GEMINI_API_KEY"
  model: "models/gemini-1.5-pro-latest"
  temperature: 0.7

# translation settings
translation:
  enabled: false

# Slack settings
slack:
  webhook_url_env: "SLACK_WEBHOOKS"
  test_mode: t
arxiv:
  categories:
    - "cs.AI" # artificial intelligence
    - "cs.LG" # machine learning
  max_results: 100
  filters:
    max_years_old: 5 # 過去X年以内の論文に絞り込む
    keywords:
      - "LLM"
      - "RAG"
      - "Finetuning"
      - "fine-tuning"
    filter_logic: "or"
