# ChatGPT設定
chatgpt:
  use_chatgpt: true
  api_key: "CHATGPT_APIKEY"
  model: "gpt-3.5-turbo"
  temperature: 0.7

# 翻訳設定
translation:
  enabled: false

# Slack設定
slack:
  webhook_url_env: "WEBHOOK_URL"
  test_mode: false
arxiv:
  categories:
    - "cs.AI" # 人工知能
    - "cs.LG" # 機械学習
    - "cs.NE" # ニューラルネットワークとニューラルコンピューティング
    - "stat.ML" # 機械学習（統計）
  max_results: 100
  filters:
    max_years_old: 5 # 過去X年以内の論文に絞り込む

    keywords:
      - "LLM"
      - "RAG"
      - "Finetuning"

    filter_logic: "or"
