# LLM settings
llm:
  provider: "gemini" # "gemini", "chatgpt", または "none" (LLMを使用しない)

gemini:
  gemini_api_key_env: "GEMINI_API_KEY"
  model: "models/gemini-2.0-flash"
  temperature: 0.7

chatgpt:
  openai_api_key_env: "OPENAI_API_KEY"
  model: "gpt-4o"
  temperature: 0.7

# Slack settings
slack:
  webhook_url_env: "SLACK_WEBHOOKS"
  test_mode: true # デバッグ用に一時的に有効化

# ArXiv settings
arxiv:
  categories:
    - "cs.AI" # artificial intelligence
    - "cs.LG" # machine learning
  max_results: 100
  filters:
    max_years_old: 5 # 過去X年以内の論文に絞り込む
    keywords:
      - "LLM"
      - "RAG"
      - "Finetuning"
      - "fine-tuning"
    filter_logic: "or"
