name: Weekly Paper Recommendation

on:
  schedule:
    - cron: "0 12 * * 4"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  post-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python with optimized caching
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt

      - name: Configure for push event (test mode)
        if: github.event_name == 'push'
        run: |
          echo "Push event detected - enabling test mode and keeping Gemini API enabled"
          sed -i 's/test_mode: false/test_mode: true/' config.yaml
          echo "Test mode enabled, but keeping Gemini API for testing"

      - name: Run paper recommendation script
        env:
          SLACK_WEBHOOKS: ${{ secrets.SLACK_WEBHOOKS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "Starting paper recommendation with improved error handling..."
          python main.py
