name: Daily Paper Recommendation

on:
  schedule:
    # - cron: "0 0 * * *"  # Daily at midnight UTC
    - cron: "0 0 */2 * *" # Every 2 days at midnight UTC
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  post-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python with optimized caching
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # より緩やかな依存関係解決を試みる
          pip install --use-pep517 -r requirements.txt

      - name: Run paper recommendation script
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOKS }}
        run: |
          python main.py
