name: Daily Paper Recommendation

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  post-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python with optimized caching
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # より緩やかな依存関係解決を試みる
          pip install --use-pep517 -r requirements.txt

      - name: Run paper recommendation script
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOKS }}
          # GitHub Actionsのイベント情報を取得
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          # pushイベントの場合はテストモードで実行
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo "Pushイベントのため、テストモードで実行します"
            sed -i 's/test_mode: false/test_mode: true/' config.yaml
          fi
          python main.py
