name: 論文自動投稿

on:
  schedule:
    # 毎日UTC 00:00 (日本時間9:00)に実行
    - cron: '0 0 * * *'
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  post-papers:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        
      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Slack Webhook URLを設定
        run: |
          # GitHub Secretsから設定ファイルに書き込み
          sed -i "s|webhook_url:.*|webhook_url: \"${{ secrets.SLACK_WEBHOOK_URL }}\"|g" config.yaml
        
      - name: 論文投稿スクリプトの実行
        run: |
          python arxiv_to_slack.py
        
      - name: 実行ログのアップロード
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: execution-logs
          path: arxiv_to_slack.log
          retention-days: 7
