name: Daily Paper Notification

on:
  schedule:
    # 毎日午前9時 (UTC) に実行（日本時間の午後6時）
    - cron: "0 9 * * *"
  workflow_dispatch: # 手動実行も可能にする

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # プロジェクトで使用するPythonのバージョンを指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./essay-recommend # requirements.txt があるディレクトリを指定

      - name: Run daily notification script
        env:
          # Slack APIトークンなどの環境変数を設定
          # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # もし翻訳にOpenAIなどを使う場合
          pass
        run: python essay-recommend/scripts/daily_notification.py # スクリプトのパスを指定
